baseurl = "https://ipixeloldc.cn"
title = "你好，这里是老C~"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = ""

[markup.highlight]
style = "github-dark"

[params]
  author = "iPixelOldC"
  info = "A Coder && Gamer (≧∇≦)ﾉ"
  description = "A Funny Portfolio~"
  keywords = "blog,developer,personal,portfolio,ipixeloldc"
  avatarurl = "img/avatar.png"
  license = '<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA-4.0</a>'
  #gravatar = "john.doe@example.com"

  #faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"
  touchIcon = "/images/apple-touch-icon.png"

  since = 2016

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/iPixelOldC/"
[[params.social]]
  name = "BIliBili"
  icon = "fa-brands fa-bilibili fa-2x"
  weight = 2
  url = "https://space.bilibili.com/"
[[params.social]]
  name = "CNBlog"
  icon = "fa-brands fa-blogger fa-2x"
  weight = 3
  url = "https://my.ipixeloldc.cn/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "https://my.ipixeloldc.cn/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "https://my.ipixeloldc.cn/about/"
[[menu.main]]
  name = "Friends"
  weight = 2
  url = "https://my.ipixeloldc.cn/friends/"
